project:
  type: website
  output-dir: docs

lang: es
  
website:
  title: "GRASS GIS 2023"
  reader-mode: false
  search: true
  navbar:
    right:
      - text: About
        href: about.qmd
      - icon: github
        aria-label: github
        href: https://github.com/veroandreo
    left:
      - text: Unidad 1
        href: unidad_1/unit1_index.qmd
      - menu:
        - href: unidad_1/intro_to_grass.qmd
        - href: unidad_1/functions_in_grass.qmd
        - href: unidad_1/explore_grass_gui.qmd
        - href: unidad_1/data_storage_and_management_in_grass.qmd
      - text: Unidad 2
        href: unidad_2/unit2_index.qmd
      - menu:
        - href: unidad_2/raster_data_in_grass.qmd
        - href: unidad_2/python_and_grass.qmd
        - href: unidad_2/imagery_data_in_grass.qmd
        - href: unidad_2/exercise_sentinel2.qmd
      - text: Unidad 3
        href: unidad_3/unit3_index.qmd
      - menu:
        - href: unidad_3/intro_obia.qmd
        - href: unidad_3/exercise_obia.qmd
      - text: Unidad 4
        href: unidad_4/unit4_index.qmd
      - menu:
        - href: unidad_4/intro_temporal.qmd
        - href: unidad_4/exercise_temporal.qmd
      - text: Unidad 5
        href: unidad_5/grass_and_r_sdm.qmd
      - text: TF
        href: trabajo_final.qmd
  page-footer:
    center: 
    - text: "&#169; 2023 Verónica Andreo, <span xmlns:cc=\"http://creativecommons.org/ns#\" xmlns:dct=\"http://purl.org/dc/terms/\">licensed under <a href=\"http://creativecommons.org/licenses/by/4.0/?ref=chooser-v1\" target=\"_blank\" rel=\"license noopener noreferrer\" style=\"display:inline-block;\">CC BY 4.0<img style=\"height:18px!important;margin-left:3px;vertical-align:text-bottom;\" src=\"https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1\"><img style=\"height:18px!important;margin-left:3px;vertical-align:text-bottom;\" src=\"https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1\"></a></p>"

execute:
  freeze: auto  # re-render only when source changes
  warning: false
  
bibliography: references.bib
csl: american-statistical-association.csl
citations-hover: true
footnotes-hover: true
knitr:
  opts_chunk: 
    collapse: true
    comment: "##"
    results: "hold"

format: 
  html:
    theme: 
      light: flatly
      dark: darkly    
    code-link: true
    code-fold: false
    code-tools: 
      toggle: true
      source: false
    self-contained: true
    toc: true
    toc-location: right
    toc-title: Contents
    #title-block-categories: true
    highlight-style: arrow
    #title-block-banner: "#546e7a"
    #title-block-banner-color: "white"
    code-block-background: true
    code-block-border-left: false
    fontsize: 12pt
    code-overflow: "scroll"
    code-line-numbers: true

    